// The runtime control rig: the game skeleton (motions/mik_skeleton.json)
// posed each frame by an Animation, producing the skinning palette for the
// glb's joints.
//
// Evaluation follows ReDIVA's rob code (the game's own logic):
// - a bone's world matrix = parentWorld * T(position) * R(rotation), where
//   the Euler channels compose as Rz * Ry * Rx in column-vector terms
//   (the game rotates a point about X first, then Y, then Z)
// - rest orientations are IDENTITY: the motion channels carry the whole
//   orientation and the skeleton's rest data only supplies translations
// - gblctr (position) and kg_ya_ex (rotation) form a global pre-root
//   transform applied to every root bone
//
// The IK chains (head/chest single-segment, arm/leg two-segment) run the
// game's solve: aim the chain root's +X at the target, then a law-of-
// cosines bend written as paired Z rotations, segments translated along
// +X (bones point down their own X axis). Chain topology comes from the
// hierarchy: node0 = the IK control bone, then its j_/e_ descendants;
// e_*_cp bones are end-effector markers whose children carry rest offsets
// measured from the marker's parent (so they get rest minus parent rest).
//
// On top of FK and IK sit the game's procedural bones (expressionId flag
// in the skeleton, all 40 ported from ReDIVA RobBlock::get_ex_rotation and
// calc_constraint): expression bones compute their Euler channels from
// other bones' channels or chain state (elbow/knee twist halves, forearm
// thirds, belly blends, static finger spreads) and constraint bones aim
// a local axis at another bone's world position (shoulder at elbow, thigh
// helper at knee, belly at chest). The arm chains also run the up-vector
// pole roll. The pole resolves by name symmetry to tl_up_kata_l/r because
// the pole byte is asymmetric in the data (left matches exactly, right
// lands two entries past its mirror).
//
// NOT evaluated: the model-space position semantics of type-1 bones (this
// skeleton has none) and the hip-fold weight scaling (not yet observed to
// matter). Foot grounding is not a runtime concern either: the animation
// loads a baked override of the leg IK-target heights that lands the feet
// (Animation.override, generated by the dump repo's tools/ground.js).
//
// Palette rule: a glb joint that IS a motion bone takes world * inverseBind.
// A joint that is not (the physics set: hair, skirt, ribbons, breast) is
// rigidly attached to its nearest animated ancestor and a rigid
// attachment's palette entry collapses to a copy of that ancestor's entry
// (world * relativeBind * inverseBind = ancestorWorld * ancestorInverseBind).
// Rigid is only the default: addOsageRig hands the joints of a chain rig
// (OsageRig) over to it and those swing instead.
class Skeleton {
  // How close an IK target may come to its chain root before the aim is abandoned and the
  // chain keeps its default pose, in metres. The game writes 1e-6 but tests it against a
  // SQUARED length, so its real threshold is the millimetre this states outright.
  static minimumAimDistance = 1e-3;

  // The objset couples these mesh bones to control-rig bones (the game's
  // skin ex-data, which the glb export cannot carry): the foot deform
  // bones follow the ankle and toe of the runtime rig. Without the
  // coupling they rigid-attach to the shin (their glb parent) and the
  // ankle rotation channels never reach the mesh.
  static MESH_BONE_DRIVERS = {
    n_asi_l_wj_ex: "kl_asi_l_wj_co",
    n_asi_r_wj_ex: "kl_asi_r_wj_co",
    n_toe_l_wj_ex: "kl_toe_l_wj",
    n_toe_r_wj_ex: "kl_toe_r_wj",
  };

  bones = [];
  palette = null;

  constructor(skeletonJson, animation, skin, nodes) {
    const { bones } = skeletonJson;
    this.bones = bones;

    const boneIndexByName = new Map(bones.map((bone, index) => [bone.name, index]));

    Rig.assertParentsFirst(bones, "Bone");

    this.globalPositionBone = boneIndexByName.get("gblctr");
    this.globalRotationBone = boneIndexByName.get("kg_ya_ex");

    // channel slots the animation tracks write into. Positions start at the
    // rest offsets and animated slots overwrite theirs every frame
    this.rotations = new Float32Array(bones.length * 3);
    this.positions = new Float32Array(bones.length * 3);

    bones.forEach((bone, index) => {
      if (bone.position) this.positions.set(bone.position, index * 3);
    });

    this.ikTargets = new Float32Array(bones.length * 3);

    this.trackSlots = this.buildTrackSlots(animation);

    // clips that play alongside the main take on this same rig, bound through
    // addClip: the baked face performance drives 35 bones the body take never
    // keys, so its tracks simply fill in more channels
    this.extraClips = [];

    // chain rigs hanging off this one, bound through addOsageRig (see
    // OsageRig): the swinging parts, which this rig has no bones for
    this.osageRigs = [];

    // IK chains: node0 = the control bone, then the j_/e_ descendants.
    // The chain root translates by node1's rest (the control bone has no
    // rest of its own), node1 sits at the root, the later nodes at segment
    // lengths along +X. isWrittenByIk marks nodes the solver owns.
    this.isWrittenByIk = new Uint8Array(bones.length);

    const firstChainChild = (index) => {
      const child = bones.findIndex((bone) => bone.parent === index && /^[je]_/.test(bone.name));
      return child < 0 ? null : child;
    };

    this.ikChains = bones.flatMap((bone, index) => {
      if (!bone.control || !bone.control.type.includes("Ik")) return [];

      const nodes = [index];
      for (let cursor = index; nodes.length < 4;) {
        const child = firstChainChild(cursor);
        if (child === null) break;
        nodes.push(child);
        cursor = child;
      }

      for (const node of nodes.slice(1)) this.isWrittenByIk[node] = 1;

      // arm chains roll their elbows toward an up-vector bone. Resolved
      // by name symmetry (see the header comment on the asymmetric byte)
      const poleName = bone.name.replace(/^c_kata/, "tl_up_kata");
      const poleBone =
        bone.control.type === "armIkRotation" ? boneIndexByName.get(poleName) : undefined;

      const segmentLength = (node) => Math.hypot(...bones[node].position);
      return [
        {
          name: bone.name,
          nodes,
          isReverse: bone.control.type === "legIkRotation",
          rootOffset: bones[nodes[1]].position,
          lengths: nodes.slice(2).map(segmentLength),
          poleBone: poleBone ?? -1,
          // solve byproducts the expression bones read: the bend angle of
          // the second segment and the aim rotation's sine/cosine pairs
          bendAngle: 0,
          aim: new Float32Array([0, 1, 0, 1]),
        },
      ];
    });

    // children of an e_*_cp effector carry rest offsets measured from the
    // effector's parent. Make them effector-relative so plain FK works
    this.fkTranslations = bones.map((bone, index) => {
      const rest = this.positions.subarray(index * 3, index * 3 + 3);
      const parent = bone.parent >= 0 ? bones[bone.parent] : null;

      if (!parent || !/^e_.*_cp$/.test(parent.name) || !bone.position || !parent.position) {
        return rest;
      }

      return Float32Array.from(
        [0, 1, 2].map((axis) => bone.position[axis] - parent.position[axis]),
      );
    });

    // the chain root carries node1's rest offset (see the header comment)
    for (const chain of this.ikChains) this.fkTranslations[chain.nodes[0]] = chain.rootOffset;

    this.worldMatrices = bones.map(() => mat4.create());
    this.globalMatrix = mat4.create();
    this.scratchMatrix = mat4.create();
    this.expressionMatrix = mat4.create();
    this.scratchVector = new Float32Array(3);

    this.buildProceduralSteps(boneIndexByName);

    // glb joints: their inverse binds and either their own motion bone or
    // the joint whose palette entry they copy (rigid attachment)
    this.skin = skin;
    this.palette = new Float32Array(skin.jointNames.length * 16);

    const parentByNode = new Map();
    nodes.forEach((node, index) =>
      node.children.forEach((child) => parentByNode.set(child, index)),
    );
    const jointByNode = new Map(skin.jointNodeIndices.map((node, joint) => [node, joint]));

    this.jointMotionBones = skin.jointNames.map((name) => {
      const driver = Skeleton.MESH_BONE_DRIVERS[name] ?? name;
      return boneIndexByName.get(driver) ?? -1;
    });

    this.jointPaletteSources = skin.jointNames.map((name, joint) => {
      if (this.jointMotionBones[joint] >= 0) return -1;

      let node = skin.jointNodeIndices[joint];

      while (parentByNode.has(node)) {
        node = parentByNode.get(node);
        const ancestorJoint = jointByNode.get(node);
        if (ancestorJoint !== undefined && this.jointMotionBones[ancestorJoint] >= 0) {
          return ancestorJoint;
        }
      }

      throw new Error(`Joint ${name} has no animated ancestor to attach to.`);
    });
  }

  // The game's procedural bones, ported from ReDIVA (get_ex_rotation and
  // calc_constraint). Expression steps run BEFORE a bone's FK compose and
  // write its Euler slots. Constraint steps run AFTER and rotate the world
  // matrix to aim a local axis at a target bone. All bone lookups resolve
  // once here. The closures only chase buffers at pose time.
  buildProceduralSteps(boneIndexByName) {
    const { bones, rotations, worldMatrices, scratchVector } = this;
    const chainByName = new Map(this.ikChains.map((chain) => [chain.name, chain]));
    const radians = (degrees) => (degrees * Math.PI) / 180;

    this.expressionSteps = new Array(bones.length).fill(null);
    this.constraintSteps = new Array(bones.length).fill(null);

    const expression = (name, step) => {
      const bone = boneIndexByName.get(name);
      if (bone === undefined) return;
      const offset = bone * 3;
      this.expressionSteps[bone] = () => step(offset);
    };

    const constraint = (name, step) => {
      const bone = boneIndexByName.get(name);
      if (bone !== undefined) this.constraintSteps[bone] = step;
    };

    const setRotation = (offset, x, y, z) => {
      rotations[offset] = x;
      rotations[offset + 1] = y;
      rotations[offset + 2] = z;
    };

    // static finger spreads (the mitten mesh opens into a relaxed hand)
    for (const side of ["l", "r"]) {
      const flip = side === "l" ? 1 : -1;
      expression(`n_hito_${side}_ex`, (o) => setRotation(o, 0, 0, radians(-9)));
      expression(`n_ko_${side}_ex`, (o) => setRotation(o, radians(-8 * flip), 0, radians(16)));
      expression(`n_kusu_${side}_ex`, (o) => setRotation(o, 0, 0, radians(9)));
      expression(`n_naka_${side}_ex`, (o) => setRotation(o, 0, 0, radians(-1)));
      expression(`n_oya_${side}_ex`, (o) =>
        setRotation(o, radians(75 * flip), radians(12 * flip), radians(-24)),
      );
    }

    for (const side of ["l", "r"]) {
      const eye = boneIndexByName.get(`kl_eye_${side}`) * 3;
      expression(`n_eye_${side}_wj_ex`, (o) =>
        setRotation(o, -rotations[eye], rotations[eye + 1] * -0.5, 0),
      );

      const wrist = boneIndexByName.get(`kl_te_${side}_wj`) * 3;
      expression(`n_ste_${side}_wj_ex`, (o) => setRotation(o, rotations[wrist], 0, 0));

      const forearmTwist = (o) => setRotation(o, BoneMath.limitAngle(rotations[wrist]) / 3, 0, 0);
      expression(`n_sude_${side}_wj_ex`, forearmTwist);
      expression(`n_sude_b_${side}_wj_ex`, forearmTwist);

      const armChain = chainByName.get(`c_kata_${side}`);
      expression(`n_hiji_${side}_wj_ex`, (o) => setRotation(o, 0, 0, armChain.bendAngle / 2));

      const legChain = chainByName.get(`cl_momo_${side}`);
      expression(`n_hiza_${side}_wj_ex`, (o) => setRotation(o, 0, 0, legChain.bendAngle / 2));

      const hip = boneIndexByName.get(`cl_momo_${side}`) * 3;
      const thighTwist = (o) =>
        setRotation(o, 0, BoneMath.limitAngle(rotations[hip + 1] + rotations[hip]) / 3, 0);
      expression(`n_momo_b_${side}_wj_ex`, thighTwist);
      expression(`n_momo_c_${side}_wj_ex`, thighTwist);

      // aim constraints: shoulder at the elbow, thigh helper away from
      // the knee and the b/c shoulder helpers lean toward n_up_kata
      constraint(`n_skata_${side}_wj_cd_ex`, (world) => {
        const elbow = worldMatrices[armChain.nodes[2]];
        BoneMath.expSetDir(world, elbow[12], elbow[13], elbow[14], scratchVector);
      });

      constraint(`n_momo_a_${side}_wj_cd_ex`, (world) => {
        const knee = worldMatrices[legChain.nodes[2]];
        BoneMath.inverseTransformPoint(world, [knee[12], knee[13], knee[14]], scratchVector);
        scratchVector[0] = -scratchVector[0];
        scratchVector[1] = -scratchVector[1];
        scratchVector[2] = -scratchVector[2];
        BoneMath.expSetDirZX(world, scratchVector);
      });

      const upperShoulder = boneIndexByName.get(`n_up_kata_${side}_ex`);
      const shoulderLean = (factor) => (world) => {
        const target = worldMatrices[upperShoulder];
        BoneMath.expSetRot(world, target[12], target[13], target[14], factor, scratchVector);
      };
      constraint(`n_skata_b_${side}_wj_cd_cu_ex`, shoulderLean(0.333));
      constraint(`n_skata_c_${side}_wj_cd_cu_ex`, shoulderLean(0.5));
    }

    // the neck follows a fifth of the head's local yaw (channel rotation
    // composed with the head chain's aim)
    const headChain = chainByName.get("cl_kao");
    const head = boneIndexByName.get("cl_kao") * 3;
    expression("n_kubi_wj_ex", (o) => {
      const local = this.expressionMatrix;
      mat4.identity(local);
      Rig.applyEuler(local, rotations, head);
      BoneMath.rotateZSinCos(local, headChain.aim[0], headChain.aim[1]);
      BoneMath.rotateYSinCos(local, headChain.aim[2], headChain.aim[3]);

      let yaw = Math.atan2(local[1], local[0]);
      if (yaw < -Math.PI / 2) yaw += Math.PI * 2;
      setRotation(o, 0, (yaw - Math.PI / 2) * 0.2, 0);
    });

    // belly blends between the chest and the hip yaw
    const chest = boneIndexByName.get("cl_mune") * 3;
    const hipYaw = boneIndexByName.get("kl_kosi_y") * 3;
    expression("n_hara_b_wj_ex", (o) =>
      setRotation(o, 0, rotations[chest + 1] / 3 + (rotations[hipYaw + 1] * 2) / 3, 0),
    );
    expression("n_hara_c_wj_ex", (o) =>
      setRotation(o, 0, (rotations[chest + 1] * 2) / 3 + rotations[hipYaw + 1] / 3, 0),
    );

    const chestBone = boneIndexByName.get("kl_mune_b_wj");
    constraint("n_hara_cd_ex", (world) => {
      const target = worldMatrices[chestBone];
      BoneMath.inverseTransformPoint(world, [target[12], target[13], target[14]], scratchVector);
      BoneMath.expSetDirZX(world, scratchVector);
    });
  }

  // The game's solve (ReDIVA RobBlock::solve_ik): aim the chain root's +X
  // axis at the target, then bend with the law of cosines as paired Z
  // rotations, translating each segment along +X. The root's stored world
  // stays unaimed (its non-chain children hang off the unaimed frame).
  solveIkChain(chain) {
    const { worldMatrices, ikTargets, globalMatrix, scratchMatrix, scratchVector } = this;
    const [root, node1, node2, node3] = chain.nodes;

    // the target channel is model-space, carried through the global transform
    const offset = root * 3;
    const x = ikTargets[offset];
    const y = ikTargets[offset + 1];
    const z = ikTargets[offset + 2];
    const targetX =
      globalMatrix[0] * x + globalMatrix[4] * y + globalMatrix[8] * z + globalMatrix[12];
    const targetY =
      globalMatrix[1] * x + globalMatrix[5] * y + globalMatrix[9] * z + globalMatrix[13];
    const targetZ =
      globalMatrix[2] * x + globalMatrix[6] * y + globalMatrix[10] * z + globalMatrix[14];

    scratchMatrix.set(worldMatrices[root]);
    BoneMath.inverseTransformPoint(scratchMatrix, [targetX, targetY, targetZ], scratchVector);

    const lengthXY = Math.hypot(scratchVector[0], scratchVector[1]);
    const length = Math.hypot(scratchVector[0], scratchVector[1], scratchVector[2]);

    chain.aim.set([0, 1, 0, 1]);

    // COMPARED AGAINST A DISTANCE, not a squared one. The game guards the same divisions
    // with 1e-6 against a SQUARED length, which is a millimetre rather than a micron and
    // taking its constant across unchanged would leave the dead zone a thousand times
    // narrower than the code it copies.
    if (lengthXY > Skeleton.minimumAimDistance && length > Skeleton.minimumAimDistance) {
      chain.aim[0] = scratchVector[1] / lengthXY;
      chain.aim[1] = scratchVector[0] / lengthXY;
      chain.aim[2] = -scratchVector[2] / length;
      chain.aim[3] = lengthXY / length;
      BoneMath.rotateZSinCos(scratchMatrix, chain.aim[0], chain.aim[1]);
      BoneMath.rotateYSinCos(scratchMatrix, chain.aim[2], chain.aim[3]);
    }

    // roll the aimed chain about its axis so the elbow leans toward the
    // up-vector bone (already posed: it precedes the chain in table order)
    if (chain.poleBone >= 0) {
      const pole = worldMatrices[chain.poleBone];
      BoneMath.inverseTransformPoint(scratchMatrix, [pole[12], pole[13], pole[14]], scratchVector);

      const lengthYZ = Math.hypot(scratchVector[1], scratchVector[2]);
      if (lengthYZ > 1e-6) {
        BoneMath.rotateXSinCos(
          scratchMatrix,
          scratchVector[2] / lengthYZ,
          scratchVector[1] / lengthYZ,
        );
      }
    }

    const world1 = worldMatrices[node1];
    world1.set(scratchMatrix);

    if (chain.nodes.length === 3) {
      const world2 = worldMatrices[node2];
      world2.set(world1);
      BoneMath.translateX(world2, chain.lengths[0]);
      return;
    }

    const [length0, length1] = chain.lengths;
    let sin0 = 0;
    let cos0 = 1;
    let sin1 = 0;
    let cos1 = -1;

    if (length > Skeleton.minimumAimDistance) {
      const projected = (length * length - length1 * length1) / length0;
      cos0 = Utilities.clamp((projected + length0) / (2 * length), -1, 1);
      cos1 = Utilities.clamp((projected - length0) / (2 * length1), -1, 1);
      sin0 = Math.sqrt(1 - cos0 * cos0);
      sin1 = Math.sqrt(1 - cos1 * cos1);

      // the reverse flag flips the bend: knees fold the other way to elbows
      if (chain.isReverse) sin0 = -sin0;
      else sin1 = -sin1;
    }

    // the elbow/knee twist helpers follow half of this bend
    chain.bendAngle = Math.atan2(sin1, cos1);

    BoneMath.rotateZSinCos(world1, sin0, cos0);

    const world2 = worldMatrices[node2];
    world2.set(world1);
    BoneMath.translateX(world2, length0);
    BoneMath.rotateZSinCos(world2, sin1, cos1);

    const world3 = worldMatrices[node3];
    world3.set(world2);
    BoneMath.translateX(world3, length1);
  }

  // one bone's compose: expression step, world = parent * T * Rz * Ry * Rx,
  // then its constraint step. Called in table order by pose.
  poseBone(bone) {
    const { bones, rotations, worldMatrices } = this;

    const expressionStep = this.expressionSteps[bone];
    if (expressionStep) expressionStep();

    const world = worldMatrices[bone];
    const parent = bones[bone].parent;
    const offset = bone * 3;

    world.set(parent < 0 ? this.globalMatrix : worldMatrices[parent]);
    mat4.translate(world, world, this.fkTranslations[bone]);
    Rig.applyEuler(world, rotations, offset);

    const constraintStep = this.constraintSteps[bone];
    if (constraintStep) constraintStep(world);
  }

  // Where each of a clip's tracks writes: one channel slot per track, picked by
  // the track's channel and resolved to an offset by its bone and axis.
  buildTrackSlots(animation) {
    return animation.tracks.map((track) => {
      const offset = track.boneIndex * 3 + track.axis;

      if (track.channel === Animation.Channels.rotation) return { buffer: this.rotations, offset };
      if (track.channel === Animation.Channels.position) return { buffer: this.positions, offset };
      return { buffer: this.ikTargets, offset };
    });
  }

  // Play another clip on this rig alongside the main take. Clips are expected
  // to drive disjoint channels (the face bake does). Where two overlap, the
  // clip bound last wins.
  addClip(animation) {
    this.extraClips.push({ animation, slots: this.buildTrackSlots(animation) });
  }

  // Hang a chain rig off this one (see OsageRig). The joints it drives stop
  // being rigid attachments here, so the chain's own motion reaches the mesh
  // instead of the bone it hangs off and pose runs it after the body bones
  // because it reads their world matrices.
  addOsageRig(skeletonJson, animation) {
    const rig = new OsageRig(skeletonJson, animation, this);

    for (const joint of rig.joints) {
      if (this.jointMotionBones[joint] >= 0) {
        throw new Error(`Joint ${this.skin.jointNames[joint]} is already a motion bone.`);
      }

      this.jointPaletteSources[joint] = -1;
    }

    this.osageRigs.push(rig);

    return rig;
  }

  pose(animation, frame) {
    const values = animation.sample(frame);
    const { trackSlots, bones, rotations, positions, worldMatrices, globalMatrix } = this;

    Rig.writeTrackValues(trackSlots, values);

    for (const clip of this.extraClips) {
      const clipValues = clip.animation.sample(frame);

      for (let track = 0; track < clip.slots.length; track++) {
        const slot = clip.slots[track];
        if (slot) slot.buffer[slot.offset] = clipValues[track];
      }
    }

    // global pre-root transform: translate by gblctr, rotate by kg_ya_ex
    const globalPosition = this.globalPositionBone * 3;
    const globalRotation = this.globalRotationBone * 3;

    mat4.identity(globalMatrix);
    mat4.translate(
      globalMatrix,
      globalMatrix,
      positions.subarray(globalPosition, globalPosition + 3),
    );
    Rig.applyEuler(globalMatrix, rotations, globalRotation);

    let nextChain = 0;

    for (let bone = 0; bone < bones.length; bone++) {
      if (bone === this.globalPositionBone || bone === this.globalRotationBone) continue;
      if (this.isWrittenByIk[bone]) continue;

      this.poseBone(bone);

      if (nextChain < this.ikChains.length && this.ikChains[nextChain].nodes[0] === bone) {
        this.solveIkChain(this.ikChains[nextChain]);
        nextChain++;
      }
    }

    const { skin, palette, jointMotionBones, jointPaletteSources } = this;

    for (let joint = 0; joint < jointMotionBones.length; joint++) {
      if (jointMotionBones[joint] < 0) continue;

      Rig.writePaletteEntry(palette, skin, joint, worldMatrices[jointMotionBones[joint]]);
    }

    for (let joint = 0; joint < jointPaletteSources.length; joint++) {
      const source = jointPaletteSources[joint];
      if (source < 0) continue;

      palette.copyWithin(joint * 16, source * 16, source * 16 + 16);
    }

    // the chains read the body bones they hang off, so they pose last
    for (const rig of this.osageRigs) rig.pose(frame);

    return palette;
  }
}
